"""empty message

Revision ID: 41dc80e4bdef
Revises: 37a5f6d7bec9
Create Date: 2019-08-28 15:26:19.631125

"""

# revision identifiers, used by Alembic.
revision = '41dc80e4bdef'
down_revision = '37a5f6d7bec9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
